@startuml
left to right direction
actor "Библиотекарь" as User1
User1 -- (Принятие книги)
User1 -- (Выдача книг)
User1 -- (Добавление новой книги)
User1 -- (Внесение даты выдачи книги и примерной даты возврата книги)
User1 -- (Внести новых читателей)
User1 -- (Видеть список книг, взятых читателем)
actor "Читатель" as User2
User2 -- (Просмотр каталога)
User2 -- (Взятие/бронирование книги)
User2 -- (Поиск книги)
@enduml