@startuml
actor "Библиотекарь" as User1
User1 -- (Добавить новую книгу в каталог)
User1 -- (Внести дату выдачи и примерную дату возврата)
User1 -- (Видеть список книг, взятых читателем)
User1 -- (Внести новых читателей)
actor "Читатель" as User2
User2 -- (Внести дату выдачи и примерную дату возврата)
User2 -- (Взять книгу из библиотеки)
@enduml